a = int(input("Enter a number: "))
b = int(input("Enter another number: "))
print("Addition", a + b)
print("Subtraction", a - b)
print("Multiplication", a * b)
print("Floor Division", a // b)
print("Division", a / b)
print("Modulus", a % b)